# Custom Language File for Launcher Customizer

[ejs.app]
title = "rezero-forest"

[ejs.landing]
mediaGitHubURL = "https://cafe.naver.com/a01village"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/invite/fZXxCdyZke"

[ejs.settings]
sourceGithubLink = "https://github.com/ckfejrdld/rezero-forest"
supportLink = "https://github.com/ckfejrdld/rezero-forest/issues"

[ejs.welcome]
welcomeHeader = "welcome To Rezero-Forest"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
